# Generated by Django 5.1.5 on 2025-01-30 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_asset'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignedAssetTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('purpose', models.TextField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('manager', models.TextField(blank=True, max_length=100, null=True)),
                ('admin', models.TextField(blank=True, max_length=100, null=True)),
                ('corporatemanager', models.TextField(blank=True, max_length=100, null=True)),
                ('business_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions_from', to='website.businessunit')),
                ('business_unitto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions_to', to='website.businessunit')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions_from', to='website.department')),
                ('departmentto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions_to', to='website.department')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='website.employee')),
            ],
        ),
        migrations.CreateModel(
            name='AssignedAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_assets', to='website.asset')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='website.assignedassettransaction')),
            ],
        ),
    ]
