# Generated by Django 5.1.5 on 2025-02-10 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_assignedassettransaction_assignedasset'),
    ]

    operations = [
        migrations.CreateModel(
            name='choices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Assigned', 'Assigned'), ('Maintenance', 'Maintenance'), ('Disposed', 'Disposed'), ('Lost', 'Lost'), ('Stolen', 'Stolen')], default='Available', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='asset',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='website.choices'),
        ),
    ]
