# Generated by Django 5.1.5 on 2025-02-10 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_choices_asset_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='choices',
            new_name='Status',
        ),
    ]
