# Generated by Django 5.1.5 on 2025-02-10 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_rename_choices_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Assigned', 'Assigned'), ('Maintenance', 'Maintenance'), ('Disposed', 'Disposed'), ('Lost', 'Lost'), ('Stolen', 'Stolen')], default='Available', max_length=20),
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
