# Generated by Django 5.1.5 on 2025-02-10 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_asset_is_archived'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='assignedasset',
            name='quantity',
        ),
        migrations.AddField(
            model_name='asset',
            name='available_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='asset',
            name='total_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assignedasset',
            name='quantity_assigned',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
