# Generated by Django 5.1.5 on 2025-02-11 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_remove_asset_quantity_remove_assignedasset_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedassettransaction',
            name='business_unitfrom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transferred_from_transactions', to='website.businessunit'),
        ),
        migrations.AddField(
            model_name='assignedassettransaction',
            name='departmentform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transferred_from_department_transactions', to='website.department'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assignedasset',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='website.assignedassettransaction'),
        ),
        migrations.AlterField(
            model_name='assignedassettransaction',
            name='business_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_transactions', to='website.businessunit'),
        ),
        migrations.AlterField(
            model_name='assignedassettransaction',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_department_transactions', to='website.department'),
        ),
    ]
