# Generated by Django 5.1.5 on 2025-02-11 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_assignedassettransaction_business_unitfrom_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignedassettransaction',
            old_name='departmentform',
            new_name='departmentfrom',
        ),
    ]
